### ISSUE TITLE
找不到地方给您发私信,就只有这里留言了

### ISSUE THREAD

**Issue by Mecil9** [Cuiks/leetcode-go#1]
您好:
看见你关于django-quill的项目,有几个问题想寻求一下帮助:
1.默认的quill输入框只有1行,怎么样设置调整这个输入框的大小
2.我想改变前端显示quill的样式,应该如何调整呢?
如有打扰,抱歉
谢谢

**Comment by cuiks** [comment]
1-1.可以重写django_quill中的"templates/django_quill/widget.html"。添加style限制height
`    <div id="quill-{{ id }}" class="django-quill-widget" data-config="{{ config }}" data-type="django-quill" style="height: 300px"></div>
`
1.2 可以通过js在页面生成quill后，调整"#quill-{{ id }}"的height。
但是我不确认上述两种方法是不是最好的，因为我没有找到相关的配置。

2.1 配置的调整可以参考django_quill和quill.js。
https://django-quill-editor.readthedocs.io/en/latest/pages/change-toolbar-configs.html
https://quilljs.com/docs/modules/, https://quilljs.com/docs/themes/
